P = PRE
W = WRITEBACK
U = UP
S = SIGNED

if bits6,5 != 0 then 
  hashlookup(00+bits6,5) = { 
    P = P, 
    W = W, 
    U = U, 
    S = S
  }

 00 01 02 03 08 09 0A 0B 0C 0D 0E 0F 10 14 18 19 1A 1B 1C 1D 1E 1F 

#define DECLARE_ARM_EMITTER_BLOCK(EMITTER) \
	/* -00---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, AND, MUL, STRH, ILL, ILL), \
    /* -01---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, ANDS, MUL, LDRH, LDRB, LDRH), \

    /* -02---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, EOR, MLA, STRH, ILL, ILL), \
    /* -03---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, EORS, MLA, LDRH, LDRB, LDRH), \

    /* -08---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, ADD, UMULL, STRH, ILL, ILL), \
    /* -09---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, ADDS, UMULL, LDRH, LDRB, LDRH), \

    /* -0A---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, ADC, UMLAL, STRH, ILL, ILL), \
    /* -0B---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, ADC, UMLAL, LDRH, LDRB, LDSH), \

    /* -0C---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, SBC, SMULL, STRHI, ILL, ILL), \
    /* -0D---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, SBC, SMULL, LDRHI, LDRBI, LDRHI), \

    /* -0E---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, RSC, SMLAL, STRHI, ILL, ILL), \
    /* -18---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, ORR, SMLAL, STRHP, ILL, ILL), \
	/* -1A---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, MOV, SMLAL, STRHPW, ILL, ILL), \
	/* -1C---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, BIC, SMLAL, STRHIP, ILL, ILL), \
	/* -1E---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, MVN, SMLAL, STRHIPW, ILL, ILL), \

    /* -0F---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, RSCS, SMLAL, LDRHI, LDRBI, LDRHI), \
	/* -19---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, ORRS, SMLAL, LDRHP, LDRBP, LDRHP), \
	/* -1B---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, MOVS, SMLAL, LDRHPW, LDRBPW, LDRHPW), \
	/* -1D---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, BICS, SMLAL, LDRHIP, LDRBIP, LDRHIP), \
	/* -1F---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, MVNS, SMLAL, LDRHIPW, LDRBIPW, LDRHIPW), \

    /* -10---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, MRS, SWP, ILL, STRHP, ILL), \

    /* -14---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, MRSR, SWPB, STRHIP, ILL, ILL), \

	
	/* -04---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, SUB, ILL, STRHI, ILL, ILL), \
	/* -05---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, SUB, ILL, LDRHI, LDRBI, LDRHI), \
	/* -06---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, RSB, ILL, STRHI, ILL, ILL), \
	/* -07---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, RSB, ILL, LDRHI, LDRBI, LDRHI), \
    /* -11---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, TST, ILL, LDRHP, LDRBP, LDRHP), \
    /* -12---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, MSR, ILL, STRHPW, ILL, ILL), \ // clashing with MSR is BX (0001) and BKPT (0111)
	/* -13---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, TEQ, ILL, LDRHPW, LDRBPW, LDRHPW), \
	/* -15---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, CMP, ILL, LDRHIP, LDRBIP, LDRHIP), \
    /* -16---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, MSRR, ILL, STRHIPW, ILL, ILL), \    
	/* -17---X- */ DECLARE_ARM_ALU_BLOCK(EMITTER, CMN, ILL, LDRHIPW, LDRBIPW, LDRHIPW), \

